services:
  siribridge:
    build: .
    container_name: siribridge
    ports:
      - "18888:18888"
    restart: always
    env_file: .env
    volumes:
      - ./siri_bridge.log:/app/siri_bridge.log:rw
