name = "siri-proxy"
main = "index.js"
compatibility_date = "2026-02-05"

kv_namespaces = [
  { binding = "USERS", id = "8f64b8d609dc41a6ae89afa06908c859" }
]

[vars]
# 这里只放非敏感的通用变量
TUNNEL_HOSTNAME = "siri.961213.xyz"
